### ISSUE TITLE
bip39 integration

### ISSUE THREAD

**Issue by evgeniy-scherbina** [rust-bitcoin/rust-wallet#7]
I try to integrate current codebase with initial bip39 implementation. I want to know if I correctly understood bip39 implementation
 
Create Wallet:
1) generate random string
2) apply aes::decrypt to it with sha2(passphrase) as a key and create mnenonic from it
3) generate seed from mnemonic
4) generate master key from seed

Decrypt Wallet:
1) generated random string was saved in DB as a plain text(during CreateWallet section).
2) user inputs passpharse
3) apply 2, 3, 4 items from CreateWallet section

RestoreWallet from mnemonic(means database was lost or damaged):
1) user inputs mnemonic
2) apply 3, 4 items from CreateWallet section

@tamasblummer do you agree with it?

**Comment by evgeniy-scherbina** [comment]
It seems that if I use RestoreWalletFromMnemonic mode I cannot recover initial randomness(and continue works in usual mode) so I have to create new wallet, and move all funds to the new wallet or every time login with the mnemonic.

**Comment by tamasblummer** [comment]
The preferred use is as follows: 
1. create random data and consider it as a cipher text. Store this cipher text in application's wallet file.
2. decrypt the cipher text using aes and with a key that is sha2 of a passphrase, the result is plain text seed.
3. generate mnemonic from plain text seed. Output this mnemonic, so user can recover from a human readable format
4. Use Hmac sha512 and an optional salt to extend plain text seed, then apply pbkdf2 to derive actual master key seed. (This step is to make mnemonic key search expensive even if partially known).
5. Derive keys from master

The application's wallet file could be re-created from mnemonic by encrypting (reverse of 2).

**Comment by tamasblummer** [comment]
KeyFactory::new_master_private_key implements above preferred use. It returns the newly generated master key, mnemonic to memorize and cipher text to store.

**Comment by tamasblummer** [comment]
See also bip32_tests how to use the methods and salt in TREZOR compatible way. The test vectors are from TREZOR.

**Comment by evgeniy-scherbina** [comment]
What should I do if I forgot passphrase and/or my db's file was damaged. I can restore master key, but I can't restore cipher text and continue works in normal mode.

**Comment by tamasblummer** [comment]
you can recover master key seed from mnemonic and create a new cipher text with any new passphrase. Cipher text is not valuable.

**Comment by tamasblummer** [comment]
Actually TREZOR tests are in mnemonic::test_mnemonic

**Comment by tamasblummer** [comment]
Mnemonic is the only valuable data here, that should be backed up and protected.

**Comment by evgeniy-scherbina** [comment]
I see earlier code here https://github.com/rust-bitcoin/rust-wallet/blob/a53a11844be3c60f9473dae461d9f1df8ff4b417/src/keyfactory.rs#L49.

It seems that passphrase only uses to decrypt cipher text, so as I understand I should input passphrase every time when I login to decrypt cipher text and restore master key.
Is it correct?

**Comment by tamasblummer** [comment]
The stored cipher text + passphrase is just an optional shortcut to master seed for applications. If cipher text or passphrase is lost then you recover by entering mnemonic and a new passphrase and create a new cipher text. There is no value in re-creating previous cipher text.

**Comment by tamasblummer** [comment]
The backup format is the mnemonic, not cipher text + passphrase.

**Comment by evgeniy-scherbina** [comment]
https://github.com/rust-bitcoin/rust-wallet/blob/a53a11844be3c60f9473dae461d9f1df8ff4b417/src/keyfactory.rs#L45

This `passphrase: &str` variable is used-defined passphrase? User should type it every time when login into the wallet?

**Comment by evgeniy-scherbina** [comment]
I understand BIP32/BIP39, I know that I can recover all my keys only from mnemonic. I try to grasp their current implementation.

**Comment by tamasblummer** [comment]
That method is to generate a new key, not to open a wallet.

To create wallet program performs steps 1-5.
To open a wallet user types in passphrase, program performs steps 2-5.
To recover a wallet user types in mnemonic and program performs Mnemonic::from(str) and reverse of 2 (encrypt with evtl. new passphrase) and 3-5.

**Comment by evgeniy-scherbina** [comment]
I've understood, I'll send PR in fee days)
